version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    - scripts/**/*
    - appspec.yml
  base-directory: build
cache: 
  paths:
    - 'node_modules/**/*'